# Generated by Django 5.1.1 on 2024-10-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_deadline_remove_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='userId',
            new_name='user',
        ),
    ]
