# Generated by Django 5.1.1 on 2024-10-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_user_task_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='userid',
            new_name='user_id',
        ),
    ]
