# Generated by Django 5.1.1 on 2024-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_user_id_task_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Scheduled', max_length=30),
        ),
    ]
